name: Test Build

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Step 1 OK"
      - uses: actions/checkout@v3
      - run: echo "Step 2 OK"
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: echo "Step 3 OK"
